# This is the configuration file for Netlify.
# It tells Netlify how to correctly build and deploy your Next.js app.

[build]
  command = "next build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
